title: Tan Si Zheng
logo: "/images/Passport photo.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Current student of NUS Graduate Diploma in System Analysis 2021. A one-year full time programme that equip learners with the latest IT knowledge and skills to stay relevant.  
  <br><br>
  
  
  
theme: jekyll-theme-minimal
google_analytics: G-52NHF643V7 # your Google Analytics tracking ID here
